docker:
  stage: docker
  image: $REGISTRY_DEVELOPMENT/build-env:latest
  services:
    - docker:dind
  variables:
    PROJECT_NAME: $CI_PROJECT_NAME
    BRANCH_NAME: $CI_BUILD_REF_NAME
  script:
    - ./.gitlab-ci/docker.sh
  only:
    - master
    - production
